# docker-compose.yml
#version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - garage-network

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./zigbee2mqtt/data:/app/data
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Раскомментировать!
    depends_on:
      - mosquitto
    networks:
      - garage-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto
      - zigbee2mqtt
    networks:
      - garage-network

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - garage-network

networks:
  garage-network:
    driver: bridge
