# zigbee-docker-compose.yml
version: '3.8'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./zigbee2mqtt/data:/app/data
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true
    network_mode: "host"  # Используем host network для простоты
